import 'dotenv/config';
import mongoose from 'mongoose';
import connectDB from './config/db.js';
import Product from './models/Product.js';
import User from './models/User.js';

const products = [
  {
    // ensure tests can look up this specific ID
    _id: new mongoose.Types.ObjectId('69988bc26491922a9205a3d5'),
    name: 'Laptop Gamer',
    category: 'Computers',
    brand: 'MSI',
    price: 1000.00,
    originalPrice: 1299.00,
    rating: 4,
    reviews: 128,
    image: '/images/laptop.jpg',
    badge: 'Best Seller',
    description: 'High-performance gaming laptop with powerful GPU and fast refresh display. Featuring the latest NVIDIA GeForce RTX 4060 graphics card, 16GB of blazing-fast DDR5 RAM, and a stunning 15.6-inch 144Hz IPS display. Whether you\'re gaming, streaming, or creating content, this laptop delivers exceptional performance in a sleek, portable design. The 512GB NVMe SSD ensures lightning-fast boot times and game loading.',
    features: ['RTX 4060 GPU', '16GB DDR5 RAM', '15.6" 144Hz Display', '512GB NVMe SSD', 'Wi-Fi 6E', 'RGB Keyboard', 'Thunderbolt 4'],
    featured: true,
    countInStock: 15,
  },
  {
    name: 'iPhone 14 Pro Max',
    category: 'Phones',
    brand: 'Apple',
    price: 1500.00,
    originalPrice: 1599.00,
    rating: 5,
    reviews: 342,
    image: '/images/iphone-14-pro-max.jpg',
    badge: 'New',
    description: "Apple's most advanced iPhone ever. The Dynamic Island transforms how you interact with your device, while the 48MP main camera captures stunning detail in every shot. Powered by the A16 Bionic chip, it handles everything from demanding games to complex AR experiences. The Always-On Display keeps important info visible at a glance, and Crash Detection can call for help when you can't.",
    features: ['A16 Bionic Chip', '48MP Camera', 'Dynamic Island', 'Always-On Display', '6.7" Super Retina XDR', 'Ceramic Shield', 'Satellite SOS'],
    featured: true,
    countInStock: 25,
  },
  {
    name: 'TV Samsung 55"',
    category: 'TVs & Displays',
    brand: 'Samsung',
    price: 800.00,
    originalPrice: 999.00,
    rating: 4,
    reviews: 89,
    image: '/images/tv-image.jpg',
    badge: '',
    description: 'Transform your living room into a home cinema with the Samsung 55-inch Crystal UHD 4K Smart TV. Powered by the Crystal Processor 4K, it upscales every scene to vibrant 4K resolution. HDR10+ delivers dynamic color and contrast, while Object Tracking Sound follows the action on screen. Access all your favorite streaming apps with the built-in Tizen smart platform.',
    features: ['4K UHD Resolution', 'Smart TV', 'HDR10+', 'Crystal Processor', 'Object Tracking Sound', 'Game Mode', 'AirSlim Design'],
    featured: true,
    countInStock: 10,
  },
  {
    name: 'Smart Watch',
    category: 'Wearables',
    brand: 'Samsung',
    price: 600.00,
    originalPrice: 749.00,
    rating: 4,
    reviews: 215,
    image: '/images/smart watch.jpg',
    badge: 'Trending',
    description: 'The ultimate smart companion for your active lifestyle. Track your workouts, monitor your heart rate, blood oxygen, and sleep patterns with medical-grade sensors. The stunning AMOLED display is bright enough for outdoor use, and the 5-day battery means you spend less time charging and more time living. Water resistant up to 50 meters for swimming and water sports.',
    features: ['Heart Rate Monitor', 'GPS Tracking', 'Water Resistant 50m', '5-Day Battery', 'AMOLED Display', 'Blood Oxygen Sensor', 'Sleep Tracking'],
    featured: true,
    countInStock: 30,
  },
  {
    name: 'Apple Earbuds',
    category: 'Audio',
    brand: 'Apple',
    price: 300.00,
    originalPrice: 349.00,
    rating: 4,
    reviews: 178,
    image: '/images/image5 earbuds.jpg',
    badge: '',
    description: 'Experience audio like never before with Apple AirPods Pro. Active Noise Cancellation blocks outside noise so you can immerse yourself in music. Transparency mode lets you hear the world around you. Personalized Spatial Audio with dynamic head tracking places sound all around you. The MagSafe charging case provides up to 30 hours of total listening time.',
    features: ['Active Noise Cancellation', 'Spatial Audio', 'MagSafe Charging', '6hr Battery', 'Transparency Mode', 'IPX4 Water Resistant', 'Adaptive EQ'],
    featured: false,
    countInStock: 40,
  },
  {
    name: 'Nvidia RTX 4090',
    category: 'Components',
    brand: 'Nvidia',
    price: 1500.00,
    originalPrice: 1799.00,
    rating: 5,
    reviews: 67,
    image: '/images/rog-strix-geforce-rtx-4090.jpg',
    badge: 'Premium',
    description: 'The ASUS ROG Strix GeForce RTX 4090 is the pinnacle of graphics performance. Built on the Ada Lovelace architecture, it features 24GB of GDDR6X memory and DLSS 3.0 with Frame Generation for unprecedented frame rates. Ray tracing reaches new heights of realism. Whether you\'re gaming at 4K, rendering 3D scenes, or training AI models, the RTX 4090 delivers uncompromising power.',
    features: ['24GB GDDR6X', 'DLSS 3.0', 'Ray Tracing', '2520 MHz Boost', 'Ada Lovelace Architecture', 'Triple Fan Cooling', 'HDMI 2.1'],
    featured: false,
    countInStock: 5,
  },
  {
    name: 'Razer Headset',
    category: 'Audio',
    brand: 'Razer',
    price: 60.00,
    originalPrice: 99.00,
    rating: 4,
    reviews: 256,
    image: '/images/casque.webp',
    badge: 'Sale',
    description: 'Dominate every game with the Razer BlackShark V2 gaming headset. THX Spatial Audio delivers pinpoint 360-degree positional accuracy so you can hear enemies before you see them. Ultra-soft memory foam ear cushions wrapped in breathable fabric keep you comfortable during marathon sessions. The detachable HyperClear cardioid mic ensures crystal-clear team communication.',
    features: ['THX Spatial Audio', 'Memory Foam', 'Noise-Isolating', 'Detachable Mic', '50mm TriForce Drivers', 'USB Sound Card', 'Lightweight 262g'],
    featured: false,
    countInStock: 50,
  },
  {
    name: 'Earphones',
    category: 'Audio',
    brand: 'Samsung',
    price: 20.00,
    rating: 3,
    reviews: 94,
    image: '/images/earphone.jpg',
    badge: '',
    description: 'Keep it simple with these reliable wired earphones from Samsung. Tuned for clear mids and deep bass, they deliver impressive sound quality at an unbeatable price. The in-line microphone lets you take calls hands-free, while the tangle-free flat cable prevents annoying knots. Multiple ear tip sizes ensure a snug, comfortable fit for all-day wear.',
    features: ['In-line Microphone', 'Tangle-Free Cable', 'Comfort Fit', 'Deep Bass', '3.5mm Jack', 'Multiple Ear Tips', 'Lightweight Design'],
    featured: false,
    countInStock: 100,
  },
  {
    name: 'Samsung SSD 1TB',
    category: 'Components',
    brand: 'Samsung',
    price: 90.00,
    originalPrice: 129.00,
    rating: 5,
    reviews: 312,
    image: '/images/samsung ssd.jpg',
    badge: 'Hot Deal',
    description: 'Upgrade your system with the Samsung 990 PRO NVMe SSD, delivering sequential read speeds up to 7,000 MB/s and write speeds up to 5,000 MB/s. The PCIe Gen 4.0 interface ensures maximum bandwidth for demanding workloads. Built with Samsung\'s latest V-NAND technology for exceptional reliability. Perfect for gamers, content creators, and professionals who demand the fastest storage available.',
    features: ['1TB Capacity', '7,000 MB/s Read', '5,000 MB/s Write', 'PCIe Gen 4', '5-Year Warranty', 'V-NAND Technology', 'Hardware Encryption'],
    featured: false,
    countInStock: 60,
  },
  {
    name: '16GB RAM',
    category: 'Components',
    brand: 'Samsung',
    price: 70.00,
    rating: 4,
    reviews: 143,
    image: '/images/ram.webp',
    badge: '',
    description: 'Boost your PC\'s performance with Samsung DDR5-5600 memory. This dual-channel 16GB kit (2x8GB) provides the bandwidth needed for smooth multitasking, gaming, and content creation. XMP 3.0 support makes overclocking easy with one-click profiles. Low latency timings ensure snappy responsiveness in all applications. Backed by Samsung\'s industry-leading memory manufacturing expertise.',
    features: ['DDR5-5600', '16GB (2x8GB)', 'XMP 3.0', 'Low Latency', 'Dual Channel', 'On-Die ECC', 'Heat Spreader'],
    featured: false,
    countInStock: 45,
  },
  {
    name: 'Monitor 24"',
    category: 'TVs & Displays',
    brand: 'Samsung',
    price: 200.00,
    originalPrice: 259.00,
    rating: 4,
    reviews: 187,
    image: '/images/monitor.jpg',
    badge: '',
    description: 'Level up your gaming setup with this 24-inch Full HD monitor featuring a blazing-fast 144Hz refresh rate. The IPS panel delivers vibrant colors and wide 178° viewing angles, while the 1ms response time eliminates ghosting and motion blur. AMD FreeSync Premium ensures tear-free gameplay. The slim bezel design is perfect for multi-monitor setups, and the adjustable stand lets you find the perfect viewing position.',
    features: ['Full HD 1080p', '144Hz Refresh', 'IPS Panel', '1ms Response Time', 'AMD FreeSync', 'Slim Bezel', 'VESA Mount'],
    featured: false,
    countInStock: 20,
  },
  {
    name: 'Tablet',
    category: 'Computers',
    brand: 'Apple',
    price: 250.00,
    originalPrice: 329.00,
    rating: 4,
    reviews: 201,
    image: '/images/tablet.jpg',
    badge: '',
    description: 'The Apple iPad is the perfect blend of power and portability. The stunning 10.9-inch Liquid Retina display brings everything to life with vivid colors and True Tone technology. Powered by the A14 Bionic chip, it handles any app with ease — from sketching with Apple Pencil to editing 4K video. With all-day battery life and support for Wi-Fi 6, it keeps you productive and entertained wherever you go.',
    features: ['10.9" Liquid Retina', 'A14 Bionic Chip', 'Apple Pencil Support', 'All-Day Battery', 'Wi-Fi 6', 'Touch ID', 'USB-C'],
    featured: false,
    countInStock: 35,
  },
  // --- Page 2 Products ---
  {
    name: 'Mechanical Keyboard',
    category: 'Accessories',
    brand: 'Razer',
    price: 130.00,
    originalPrice: 169.00,
    rating: 5,
    reviews: 389,
    image: 'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=600&q=80',
    badge: 'Best Seller',
    description: 'Take your typing and gaming to the next level with the Razer Huntsman V2 mechanical keyboard. Featuring Razer Optical Switches with near-zero debounce delay, every keystroke registers at the speed of light. The doubleshot PBT keycaps resist shine and fading, while the detachable wrist rest keeps you comfortable during long sessions. Customizable RGB lighting with Razer Chroma brings your setup to life.',
    features: ['Optical Switches', 'PBT Keycaps', 'RGB Chroma', 'Detachable Wrist Rest', 'N-Key Rollover', 'On-Board Memory', 'USB-C'],
    featured: false,
    countInStock: 42,
  },
  {
    name: 'Gaming Mouse',
    category: 'Accessories',
    brand: 'Razer',
    price: 80.00,
    originalPrice: 99.00,
    rating: 5,
    reviews: 512,
    image: 'https://images.unsplash.com/photo-1527814050087-3793815479db?w=600&q=80',
    badge: 'Trending',
    description: 'Precision meets performance with the Razer DeathAdder V3. Engineered with an ultra-lightweight 59g design and the Focus Pro 30K optical sensor, this mouse delivers flawless tracking on any surface. The ergonomic shape fits naturally in your hand, reducing fatigue during competitive gaming sessions. Razer HyperSpeed wireless technology ensures a lag-free connection.',
    features: ['30K DPI Sensor', '59g Ultralight', 'Wireless HyperSpeed', '90hr Battery', 'Optical Switches', 'Ergonomic Design', 'Speedflex Cable'],
    featured: false,
    countInStock: 55,
  },
  {
    name: 'Webcam 4K',
    category: 'Accessories',
    brand: 'Samsung',
    price: 150.00,
    rating: 4,
    reviews: 134,
    image: 'https://images.unsplash.com/photo-1623949556303-b0d17d198863?w=600&q=80',
    badge: '',
    description: 'Look your best on every video call with this premium 4K webcam. The Sony STARVIS sensor captures stunning detail even in low light, while the built-in ring light provides flattering illumination. Auto-framing AI keeps you centered in the frame as you move. Dual omnidirectional microphones with noise cancellation ensure crystal-clear audio for meetings and streaming.',
    features: ['4K 30fps / 1080p 60fps', 'Sony STARVIS Sensor', 'Built-in Ring Light', 'Auto-Framing AI', 'Dual Microphones', 'Noise Cancellation', 'USB-C Plug & Play'],
    featured: false,
    countInStock: 28,
  },
  {
    name: 'Portable SSD 2TB',
    category: 'Components',
    brand: 'Samsung',
    price: 180.00,
    originalPrice: 229.00,
    rating: 5,
    reviews: 276,
    image: 'https://images.unsplash.com/photo-1610415394675-22121ca0de23?w=600&q=80',
    badge: 'Hot Deal',
    description: 'Take your data anywhere with the Samsung T7 Shield portable SSD. With a rugged, IP65-rated design, it withstands drops, dust, and water. Transfer speeds up to 1,050 MB/s mean you can move large files in seconds. The compact, palm-sized form factor slips easily into any pocket or bag. AES 256-bit hardware encryption keeps your data secure on the go.',
    features: ['2TB Capacity', '1,050 MB/s Transfer', 'IP65 Dust & Water Resistant', 'Drop Resistant (3m)', 'AES 256-bit Encryption', 'USB 3.2 Gen 2', 'Palm-Sized Design'],
    featured: false,
    countInStock: 38,
  },
  {
    name: 'Bluetooth Speaker',
    category: 'Audio',
    brand: 'Samsung',
    price: 45.00,
    rating: 4,
    reviews: 198,
    image: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600&q=80',
    badge: '',
    description: 'Fill any room with rich, 360-degree sound from this portable Bluetooth speaker. The dual-driver design delivers deep bass and crisp highs with surprising volume for its compact size. IPX7 waterproof rating means pool parties and beach trips are no problem. Up to 20 hours of playtime on a single charge, and you can pair two speakers for stereo sound.',
    features: ['360° Sound', 'IPX7 Waterproof', '20hr Battery', 'Bluetooth 5.3', 'Stereo Pairing', 'Built-in Mic', 'USB-C Charging'],
    featured: false,
    countInStock: 75,
  },
  {
    name: 'Drone Camera',
    category: 'Gadgets',
    brand: 'Other',
    price: 450.00,
    originalPrice: 599.00,
    rating: 4,
    reviews: 87,
    image: 'https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=600&q=80',
    badge: 'Sale',
    description: 'Capture breathtaking aerial footage with this compact folding drone. The 4K HDR camera with a 1/1.3" CMOS sensor shoots stunning photos and cinematic video stabilized by a 3-axis gimbal. Intelligent flight modes like ActiveTrack, Hyperlapse, and MasterShots make professional-quality content effortless. With 46 minutes of flight time and obstacle sensing in all directions, you can fly with confidence.',
    features: ['4K HDR Camera', '3-Axis Gimbal', '46min Flight Time', 'Obstacle Sensing', 'ActiveTrack 5.0', 'Foldable Design', '12km Video Transmission'],
    featured: false,
    countInStock: 12,
  },
  {
    name: 'Wireless Charger Pad',
    category: 'Accessories',
    brand: 'Apple',
    price: 35.00,
    rating: 4,
    reviews: 421,
    image: 'https://images.unsplash.com/photo-1591290619618-904f6dd935e3?w=600&q=80',
    badge: '',
    description: 'Simplify charging with this sleek MagSafe-compatible wireless charging pad. Just place your phone on the pad and it snaps into perfect alignment with powerful magnets. Charges iPhone up to 15W and AirPods at 7.5W. The premium aluminum and glass construction looks great on any desk or nightstand. LED indicator shows charging status at a glance.',
    features: ['15W Fast Charge', 'MagSafe Compatible', 'Qi Certified', 'LED Indicator', 'Foreign Object Detection', 'Anti-Slip Base', 'Ultra-Slim Design'],
    featured: false,
    countInStock: 90,
  },
  {
    name: 'VR Headset',
    category: 'Gadgets',
    brand: 'Other',
    price: 350.00,
    originalPrice: 449.00,
    rating: 4,
    reviews: 156,
    image: 'https://images.unsplash.com/photo-1622979135225-d2ba269cf1ac?w=600&q=80',
    badge: 'New',
    description: 'Step into new worlds with this standalone VR headset — no PC or console required. The dual LCD displays deliver a crisp 4K+ resolution at 120Hz for smooth, immersive experiences. Inside-out tracking with hand gesture support means no external sensors needed. Access hundreds of games, fitness apps, social experiences, and immersive videos from the built-in store.',
    features: ['4K+ Resolution', '120Hz Refresh', 'Standalone (No PC)', 'Hand Tracking', '256GB Storage', '2hr Battery Life', 'Passthrough Mode'],
    featured: false,
    countInStock: 18,
  },
  {
    name: 'USB-C Hub 10-in-1',
    category: 'Accessories',
    brand: 'Other',
    price: 55.00,
    rating: 4,
    reviews: 334,
    image: 'https://images.pexels.com/photos/4195404/pexels-photo-4195404.jpeg?auto=compress&cs=tinysrgb&w=600',
    badge: '',
    description: 'Expand your laptop\'s connectivity with this premium 10-in-1 USB-C hub. Features include 4K HDMI output, Gigabit Ethernet, 100W Power Delivery passthrough, SD and microSD card readers, and multiple USB-A and USB-C data ports. The aluminum unibody design dissipates heat efficiently and matches modern laptops perfectly. Plug-and-play with no drivers needed.',
    features: ['4K HDMI', 'Gigabit Ethernet', '100W PD Passthrough', 'SD / microSD Reader', '3x USB-A 3.0', 'USB-C Data Port', 'Aluminum Body'],
    featured: false,
    countInStock: 65,
  },
  {
    name: 'Smart Home Speaker',
    category: 'Audio',
    brand: 'Apple',
    price: 200.00,
    originalPrice: 249.00,
    rating: 5,
    reviews: 267,
    image: 'https://images.unsplash.com/photo-1558089687-f282ffcbc126?w=600&q=80',
    badge: 'Premium',
    description: 'The Apple HomePod brings room-filling, high-fidelity audio to your smart home. Computational audio uses advanced software to analyze and optimize the music in real time. Siri integration lets you control your smart home devices, set timers, play music, and more with just your voice. With Matter support, it serves as a home hub for connected devices from any brand.',
    features: ['High-Fidelity Audio', 'Siri Built-in', 'Smart Home Hub', 'Matter Support', 'Spatial Audio', 'Temperature & Humidity Sensor', 'Multi-Room Audio'],
    featured: false,
    countInStock: 22,
  },
  {
    name: 'Action Camera',
    category: 'Gadgets',
    brand: 'Other',
    price: 300.00,
    originalPrice: 399.00,
    rating: 5,
    reviews: 445,
    image: 'https://images.unsplash.com/photo-1564466809058-bf4114d55352?w=600&q=80',
    badge: 'Best Seller',
    description: 'Record every adventure in stunning 5.3K resolution with this rugged action camera. HyperSmooth 6.0 stabilization delivers incredibly smooth footage even during extreme activities. The waterproof design works down to 33ft without a housing. The front-facing screen makes vlogging easy, while HindSight captures 30 seconds before you press record so you never miss a moment.',
    features: ['5.3K 60fps Video', 'HyperSmooth 6.0', 'Waterproof 33ft', 'Front LCD Screen', 'HindSight Capture', '27MP Photos', 'Voice Control'],
    featured: false,
    countInStock: 30,
  },
  {
    name: 'Power Bank 20000mAh',
    category: 'Accessories',
    brand: 'Samsung',
    price: 40.00,
    rating: 4,
    reviews: 523,
    image: 'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=600&q=80',
    badge: '',
    description: 'Never run out of power with this high-capacity 20,000mAh portable charger. Equipped with 65W USB-C Power Delivery, it can fast-charge your laptop, phone, and tablet simultaneously through its three output ports. The LED display shows remaining battery percentage at a glance. Airline-approved capacity means you can take it on any flight.',
    features: ['20,000mAh Capacity', '65W USB-C PD', '3 Output Ports', 'LED Display', 'Airline Approved', 'Pass-Through Charging', 'Compact Design'],
    featured: false,
    countInStock: 80,
  },
];

const seedDB = async () => {
  try {
    await connectDB();

    // Clear existing products
    await Product.deleteMany({});
    console.log('Cleared existing products');

    // Insert seed data
    const created = await Product.insertMany(products);
    console.log(`Seeded ${created.length} products`);

    // Create admin user (skip if already exists)
    const existingAdmin = await User.findOne({ email: 'admin@electrostore.com' });
    if (!existingAdmin) {
      await User.create({
        username: 'admin',
        email: 'admin@electrostore.com',
        password: 'admin123',
        firstName: 'Admin',
        lastName: 'User',
        isAdmin: true,
      });
      console.log('Created admin user: admin@electrostore.com / admin123');
    } else {
      console.log('Admin user already exists');
    }

    process.exit(0);
  } catch (error) {
    console.error('Seed error:', error.message);
    process.exit(1);
  }
};

seedDB();
